// <auto-generated />
using System;
using EtteplanMORE.ServiceManual.ApplicationCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EtteplanMORE.ServiceManual.ApplicationCore.Migrations
{
    [DbContext(typeof(FactoryDeviceDbContext))]
    [Migration("20200125105613_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EtteplanMORE.ServiceManual.ApplicationCore.Entities.FactoryDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("EtteplanMORE.ServiceManual.ApplicationCore.Entities.FactoryDeviceMaintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("FactoryDeviceId");

                    b.Property<bool>("Fixed");

                    b.Property<DateTime>("TimeReported");

                    b.Property<int>("UrgencyLevel");

                    b.HasKey("Id");

                    b.HasIndex("FactoryDeviceId");

                    b.ToTable("Maintenances");
                });

            modelBuilder.Entity("EtteplanMORE.ServiceManual.ApplicationCore.Entities.FactoryDeviceMaintenance", b =>
                {
                    b.HasOne("EtteplanMORE.ServiceManual.ApplicationCore.Entities.FactoryDevice")
                        .WithMany("Maintenances")
                        .HasForeignKey("FactoryDeviceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
